version: "3.5"

services:

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./www:/code
            - ./php72:/usr/local/etc/php
        working_dir: /code
        stdin_open: true
        tty: true
        depends_on:
            - mongodb
        networks:
            - frontend
            - backend    
        ports:
            - "8000:8000"
        command: bash -c "sleep 10; php artisan serve --host=0.0.0.0" 

        
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./db/mongodb:/data/db
        networks:
            - backend
        
networks:
  frontend:
    name: broccoli_server
  backend: